cache:
  directories:
    - /var/cache/apt/archives/*.deb
  
language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update -qq
    
install:
  - sudo apt-get -y -qq install qt58base qt58declarative qt58quickcontrols2 qt58svg qt58webengine qt58graphicaleffects qt58qbs
  - source /opt/qt58/bin/qt58-env.sh

script:
  - mkdir -p ./appdir
  - git submodule update --init --recursive
  - mkdir deps
  - cd deps
  - git clone -b develop https://github.com/lirios/fluid
  - cd fluid
  - git submodule update --init
  - ./scripts/fetch_icons.sh
  - mkdir build
  - cd build
  - qmake CONFIG+=install_under_qt ../fluid.pro
  - make -j4
  - sudo make install
  - cd ../../../
  - mkdir build
  - qbs setup-toolchains --type gcc /usr/bin/g++ gcc
  - qbs setup-qt $(which qmake) travis-qt5
  - qbs config profiles.travis-qt5.baseProfile gcc
  - qbs -d build -j $(nproc) profile:travis-qt5 project.withFluid:false qbs.installRoot:appdir qbs.installPrefix:usr
  - sudo chown -R $USER appdir ; find appdir/
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -qmldir=. -verbose=2
  - rm ./appdir/io.liri.Browser.png # Workaround for linuxedeloyqt bug
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -qmldir=. -verbose=2
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./Liri_Browser*.AppImage https://transfer.sh/Liri_Browser-git.$(git rev-parse --short HEAD)-x86_64.AppImage

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
