cache:
  directories:
    - /var/cache/apt/archives/*.deb
  
language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update -qq
    
install:
  - sudo apt-get -y install qt58base qt58declarative qt58quickcontrols2 qt58svg qt58webengine qt58graphicaleffects
  - source /opt/qt58/bin/qt58-env.sh

script:
  - mkdir -p ./appdir
  - git clone -b develop https://github.com/lirios/fluid
  - cd fluid
  - git submodule update --init
  - mkdir build
  - cd build
  - qmake CONFIG+=use_qt_paths ..
  - make -j4
  - sudo make install
  - find ..
  - # sudo make INSTALL_ROOT=../../appdir install ; sudo chown -R $USER ../../appdir ; find ../../appdir/
  - cd ../../
  - git clone https://github.com/tim-sueberkrueb/slime-engine
  - cd slime-engine
  - qmake CONFIG+=use_qt_paths
  - make -j4
  - sudo make install
  - # sudo make INSTALL_ROOT=../appdir install ; sudo chown -R $USER ../appdir ; find ../appdir/
  - cd ../
  - mkdir build
  - cd build
  - qmake LIRI_INSTALL_PREFIX=/usr CONFIG+=QTWEBENGINE_ENABLED ..
  - make -j4
  - sudo make INSTALL_ROOT=../appdir install ; sudo chown -R $USER ../appdir ; find ../appdir/
  - cd ../
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -qmldir=. -qmldir=slime-engine/modules/SlimeEngine/qmldir -verbose=2
  - rm ./appdir/io.liri.Browser.png # Workaround for linuxedeloyqt bug
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage -qmldir=. -qmldir=slime-engine/modules/SlimeEngine/qmldir -verbose=2
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./Liri_Browser*.AppImage https://transfer.sh/Liri_Browser-git.$(git rev-parse --short HEAD)-x86_64.AppImage
